[package]
name = "clap-doc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap_builder = { version = "4.5.17", default-features = false, features = ["std"] }
stackstack = "0.3.0"

[dev-dependencies]
clap = { version = "4.5.17", features = ["derive"] }
expect-test = "1.5.0"
indoc = "2.0.5"
